[package]
name = "pdq"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pdq"
path = "src/bin/pdq.rs"


[dependencies]
arrow = "55.2.0"
async-trait = "0.1"
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.10"
fst = "0.4.7"
rayon = "1.8"
tokio = { version = "1.46", features = ["rt-multi-thread", "macros", "fs"] }
walkdir = "2.5"
memmap2 = "0.9"
futures = "0.3"
datafusion = { features = [
    "backtrace",
    "parquet",
], git = "https://github.com/apache/datafusion.git" }
parquet = { version = "55.2.0", default-features = false, features = [
    "arrow",
    "async",
    "object_store",
    "encryption",
] }
object_store = "0.12.2"
bytes = "1.10.1"
anyhow = "1.0.98"
tracing = "0.1.41"


[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.8"
