[package]
name = "pdq"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/erichutchins/pdq"
readme = "README.md"

[lib]
name = "pdq"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "pdq"
path = "src/bin/pdq.rs"

[dependencies]
arrow = "55.2.0"
arrow-pyarrow = "55.2.0"
async-trait = "0.1"
clap = { version = "4.0", features = ["derive"] }
fst = "0.4.7"
rayon = "1.10"
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros", "fs"] }
# PyO3 dependencies for Python bindings
pyo3 = { version = "0.24", features = [
    "extension-module",
    "abi3-py39",
    "anyhow",
] }
pyo3-async-runtimes = { version = "0.24", features = ["tokio-runtime"] }
pyo3-async-runtimes-macros = { version = "0.24" }
datafusion = { default-features = false, features = [
    "parquet",
], version = "49.0.0" }
datafusion-common = "49.0.0"
datafusion-physical-expr = "49.0.0"
datafusion-expr = "49.0.0"
walkdir = "2.5"
memmap2 = "0.9"
futures = "0.3"
parquet = { version = "55.2.0", default-features = false, features = [
    "arrow",
    "async",
    "brotli",
    "encryption",
    "flate2",
    "lz4",
    "object_store",
    "snap",
    "zstd",
] }
object_store = "0.12"
bytes = "1.10"
anyhow = "1.0.98"


[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.8"


# Python-specific build configuration
[package.metadata.maturin]
name = "pdq"
python-source = "python"
